version: '3'
services:
  golang-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: golang-server
    ports:
      - "9091:8080"
    volumes:
      - .:/go/src/sample_docker_compose
